### ISSUE TITLE
Mesh rendering problem with  > v3.2.1r1 in Ubuntu 16.04

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/osg-dae#3]
I am not able to render DAE files in the gepetto viewer. I have installed both gepetto viewer and plugin using robotpkg.

@jmirabel and @nim65s do you know how I can fix this issue?

**Comment by jmirabel** [comment]
I never tested this plugin with other version than 3.2. On my computer, I use 3.4.

The quick and dirty solution is to download the source of OSG for the version that suits you. Then compile without installing by making sure you compile the DAE plugin. Finally, copy the libosgdg_dae.so to the lib/osgPlugins-3.4.0/ directory.

**Comment by jmirabel** [comment]
@nim65s It should not be hard in robotpkg to compile the DAE plugin directly from the OSG sources, without this package. Running `make install` in `build/src/osgPlugins/dae` does the trick.

**Comment by cmastalli** [comment]
@jmirabel  -- I followed your dirty trick, however I still have the same rendering problem. The collada rendering is much bigger and almost black.

Do you think is a problem with my PC? Note that STL files render well.

**Comment by jmirabel** [comment]
What version of OSG do you use ?

**Comment by cmastalli** [comment]
3.2.1

**Comment by jmirabel** [comment]
Then robotpkg should work. What was the original issue / error message ?

**Comment by jmirabel** [comment]
Do you have /opt/openrobots/lib in your LD_LIBRARY_PATH ?

**Comment by cmastalli** [comment]
I have a rendering problem with DAE files, it used to work before.

I have defined the /opt/openrobots/lib in LD_LIBRARY_PATH?

**Comment by jmirabel** [comment]
> I have a rendering problem with DAE files,

I understand that. Could you be more explicit ?

**Comment by cmastalli** [comment]
> > I have a rendering problem with DAE files,
> 
> I understand that. Could you be more explicit ?

The mesh render is around 1000 times bigger and it looks that the texture is not rendered.

**Comment by jmirabel** [comment]
Are you sure this is GV's fault ?

**Comment by cmastalli** [comment]
> Are you sure this is GV's fault ?

Not really, but everything else works well (i.e. rendering of arrows, spheres and STL files)

**Comment by jmirabel** [comment]
Convert the model that causes you issues to STL to check whether it is related to the format.

**Comment by guru-florida** [comment]
Hi @cmastalli. The 1000x Issue is because the DAE plugin in not respecting the <unit name...meter...> spec in the <asset> section. For example:
```
<asset>
    <unit name="millimeter" meter="0.001"/>
</asset>

```
I have confirmed this in Gepetto Viewer 4.8. I re-exported my DAEs using Blender with the units set to meters and it now loads fine. 

@jmirabel What do you think the effort would be to support the <unit> tag?  The unit tag has the scaler ex. 0.001 for millimeters, so it's a matter of holding on to that scalar and applying it to all the float_array values/etc.

The texture is also very white for me. It seems that GV uses a much brighter ambient light than RViz which seems to be "at dusk". I feel RViz is more off on the lighting though than GV. Blender seems to render coloring like GV if you switch the View Shading selector (top right of viewport) to actual "Render Preview"....my models become whited-out because I tuned materials for RViz.

**Comment by guru-florida** [comment]
Yes, GV is respecting lighting from within DAE models. While exporting my original DAEs I had a number of lights in the DAEs I didnt know I was exporting as well. I re-exported all my DAEs removing any lighting in Blender from export. I also went into the GV Body Tree and turned LightingMode to OFF for the "world" object. This got me the same look as in RViz. As mentioned RViz does not use any lighting from within DAEs and doesnt seem to have any considerable lighting built-in.

So I would conclude GV is works-as-designed as far as texture rendering but RViz should do something about lighting.

**Comment by jmirabel** [comment]
> @jmirabel What do you think the effort would be to support the tag? The unit tag has the scaler ex. 0.001 for millimeters, so it's a matter of holding on to that scalar and applying it to all the float_array values/etc.

OSG supports the unit asset. Looking at the source code of OSG, the unit is read and stored in a map but it is left to the user to apply it... i will provide a fix.

> Yes, GV is respecting lighting from within DAE models.

It does. If this annoys you, you can call `gui.callVoidProperty("meshname", "RemoveLightSources")`.

**Comment by guru-florida** [comment]
Thank you @jmirabel! That was fast. :)  

Also thanks for the tip on the RemoveLightSources.
